
export const API_KEY = 'AIzaSyA-YPaxiwk03VMrQcYgD4ly0IfouCApjHw'

//constants

export const FETCH_HOSPITAL_SUCCESS = 'FETCH_HOSPITAL_SUCCESS'
export const FETCH_HOSPITAL_FAILURE = 'FETCH_HOSPITAL_FAILURE'
export const FETCH_ADDRESS_SUCCESS = 'FETCH_ADDRESS_SUCCESS'
export const FETCH_ADDRESS_FAILURE = 'FETCH_ADDRESS_FAILURE'

export const GET_NEWS_SUCCESS = 'GET_NEWS_SUCCESS'
export const GET_NEWS_FAILURE = 'GET_NEWS_FAILURE'

export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_FAILURE = 'GET_USER_FAILURE'

export const GET_HISTORY_SUCCESS = 'GET_HISTORY_SUCCESS'